package com.example.medivault.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors
val LightPrimary = Color(0xFF00796B)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFB2DFDB)
val LightOnPrimaryContainer = Color(0xFF004D40)
val LightSecondary = Color(0xFF00897B)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFE0F2F1)
val LightOnSecondaryContainer = Color(0xFF004D40)
val LightTertiary = Color(0xFF455A64)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFCFD8DC)
val LightOnTertiaryContainer = Color(0xFF263238)
val LightBackground = Color(0xFFFAFDFB)
val LightOnBackground = Color(0xFF191C1B)
val LightSurface = Color(0xFFFAFDFB)
val LightOnSurface = Color(0xFF191C1B)
val LightSurfaceVariant = Color(0xFFDAE5E1)
val LightOnSurfaceVariant = Color(0xFF3F4946)
val LightOutline = Color(0xFF6F7976)

// Dark Theme Colors
val DarkPrimary = Color(0xFF80CBC4)
val DarkOnPrimary = Color(0xFF003730)
val DarkPrimaryContainer = Color(0xFF005047)
val DarkOnPrimaryContainer = Color(0xFFB2DFDB)
val DarkSecondary = Color(0xFF4DB6AC)
val DarkOnSecondary = Color(0xFF003730)
val DarkSecondaryContainer = Color(0xFF004D40)
val DarkOnSecondaryContainer = Color(0xFFE0F2F1)
val DarkTertiary = Color(0xFFB0BEC5)
val DarkOnTertiary = Color(0xFF1C2D35)
val DarkTertiaryContainer = Color(0xFF37474F)
val DarkOnTertiaryContainer = Color(0xFFCFD8DC)
val DarkBackground = Color(0xFF191C1B)
val DarkOnBackground = Color(0xFFE1E3E1)
val DarkSurface = Color(0xFF191C1B)
val DarkOnSurface = Color(0xFFE1E3E1)
val DarkSurfaceVariant = Color(0xFF3F4946)
val DarkOnSurfaceVariant = Color(0xFFDAE5E1)
val DarkOutline = Color(0xFF89938F)
